/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author adria
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxPlano = new javax.swing.JComboBox<>();
        lblPlano = new javax.swing.JLabel();
        btbCadastrese = new javax.swing.JButton();
        txtCpf = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        lblNomeApelido = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtCadastro = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        lblSenha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxPlano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Plano", "Plano Completo", "Plano Individual" }));
        cbxPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPlanoActionPerformed(evt);
            }
        });
        getContentPane().add(cbxPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        lblPlano.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblPlano.setForeground(new java.awt.Color(255, 255, 255));
        lblPlano.setText("Plano");
        getContentPane().add(lblPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 120, 20));

        btbCadastrese.setBackground(new java.awt.Color(153, 153, 153));
        btbCadastrese.setText("CADASTRE-SE");
        btbCadastrese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCadastreseActionPerformed(evt);
            }
        });
        getContentPane().add(btbCadastrese, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 190, 50));

        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 220, -1));

        lblCpf.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(255, 255, 255));
        lblCpf.setText("CPF");
        getContentPane().add(lblCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 100, 20));

        lblNomeApelido.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblNomeApelido.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeApelido.setText("Nome ou apelido");
        getContentPane().add(lblNomeApelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 100, 20));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 220, -1));

        lblDataNascimento.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        lblDataNascimento.setForeground(new java.awt.Color(255, 255, 255));
        lblDataNascimento.setText("Data de Nascimento");
        getContentPane().add(lblDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 130, 20));
        getContentPane().add(txtDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 220, -1));

        lblEmail.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("E-mail");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 220, -1));

        txtCadastro.setBackground(new java.awt.Color(153, 153, 153));
        txtCadastro.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtCadastro.setText("Cadastro");
        txtCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 120, 50));

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 220, -1));

        lblSenha.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha");
        getContentPane().add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/painel-login.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 540, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/projeto facul.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -3, 1010, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastroActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void cbxPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPlanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPlanoActionPerformed

    private void btbCadastreseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCadastreseActionPerformed
      String n, c, d, e, s, p;
        n = txtNome.getText();
        c = txtCpf.getText();
        d = txtDataNascimento.getText();
        e = txtEmail.getText();
        s = txtSenha.getText();
        p = cbxPlano.getSelectedItem().toString();

        if (c.isEmpty()) { // se usuário está vazio
            JOptionPane.showMessageDialog(null, "É obrigatório digitar o CPF");
            txtCpf.requestFocus();
            return; // stop
        }
        if (n.isEmpty()) { // se senha está vazia
            JOptionPane.showMessageDialog(null, "É obrigatório digitar o Nome");
            txtNome.requestFocus();
            return; // stop
        }
        if (s.isEmpty()) { // se senha está vazia
            JOptionPane.showMessageDialog(null, "É obrigatório digitar a Senha");
            txtSenha.requestFocus();
            return; // stop
        }
        try {
            //2 - Conectar no banco de dados sistemabd
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3307/sistemabd", "root", "171246@Njo");
            //Executar a operação desejada (INSERT, UPDATE, DELETE, SELECT)
            PreparedStatement st = conectado.prepareStatement("INSERT INTO tb_clientes VALUES(?,?,?,?,?,?)");
            st.setString(1, n);
            st.setString(2, c);
            st.setString(3, e);
            st.setString(4, s);
            st.setString(5, p);
            st.setString(6, d);
            
            
            
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso");
            txtNome.setText("");
            txtCpf.setText("");
            txtDataNascimento.setText("");
            txtEmail.requestFocus();
            cbxPlano.setSelectedIndex(0);
            txtSenha.setText("");
            

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Mensagem de erro: " + ex.getMessage());
        } catch (SQLException ex) {
            int erro = ex.getErrorCode();
            if (erro == 1062) {
                JOptionPane.showMessageDialog(null, "Usuário Já cadastrado");
                txtCpf.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Entre em contato com o administrador do sistema e informe o erro: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btbCadastreseActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCadastrese;
    private javax.swing.JComboBox<String> cbxPlano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNomeApelido;
    private javax.swing.JLabel lblPlano;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtCadastro;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
